import { env } from 'cloudflare:workers';
import { getChatGPTUser } from '../../chatgpt-auth';

const schemaSql = `CREATE TABLE IF NOT EXISTS cards (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id TEXT NOT NULL, japanese TEXT NOT NULL, english TEXT NOT NULL, example TEXT, note TEXT, tag TEXT NOT NULL DEFAULT 'CSV登録', next_review_at INTEGER NOT NULL, created_at INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS review_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, card_id INTEGER NOT NULL, direction TEXT NOT NULL, result INTEGER NOT NULL, reviewed_at INTEGER NOT NULL);`;

async function db() { await env.DB.prepare('CREATE TABLE IF NOT EXISTS cards (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id TEXT NOT NULL, japanese TEXT NOT NULL, english TEXT NOT NULL, example TEXT, note TEXT, tag TEXT NOT NULL DEFAULT \'CSV登録\', next_review_at INTEGER NOT NULL, created_at INTEGER NOT NULL)').run(); try { await env.DB.prepare("ALTER TABLE cards ADD COLUMN tag TEXT NOT NULL DEFAULT 'CSV登録'").run(); } catch {} await env.DB.prepare('CREATE TABLE IF NOT EXISTS review_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, card_id INTEGER NOT NULL, direction TEXT NOT NULL, result INTEGER NOT NULL, reviewed_at INTEGER NOT NULL)').run(); return env.DB; }

export async function GET() { const user=await getChatGPTUser(); if(!user)return Response.json({error:'ログインが必要です'},{status:401}); const d=await db(); const result=await d.prepare('SELECT id, japanese AS ja, english AS en, tag, next_review_at AS nextReviewAt, created_at AS createdAt FROM cards WHERE user_id = ? ORDER BY next_review_at ASC').bind(user.userId).all(); return Response.json(result.results); }

export async function POST(request:Request) { const user=await getChatGPTUser(); if(!user)return Response.json({error:'ログインが必要です'},{status:401}); const body=await request.json() as { japanese?:string; english?:string; tag?:string; example?:string; note?:string }; if(!body.japanese||!body.english)return Response.json({error:'日本語と英語は必須です'},{status:400}); const d=await db(); const now=Date.now(); const result=await d.prepare('INSERT INTO cards (user_id,japanese,english,tag,example,note,next_review_at,created_at) VALUES (?,?,?,?,?,?,?,?)').bind(user.userId,body.japanese,body.english,body.tag||'CSV登録',body.example||null,body.note||null,now,now).run(); return Response.json({id:result.meta.last_row_id},{status:201}); }

export async function PATCH(request:Request) { const user=await getChatGPTUser(); if(!user)return Response.json({error:'ログインが必要です'},{status:401}); const body=await request.json() as {id?:number;direction?:string;result?:boolean;nextReviewAt?:number}; if(!body.id)return Response.json({error:'カードIDが必要です'},{status:400}); const d=await db(); await d.prepare('UPDATE cards SET next_review_at=? WHERE id=? AND user_id=?').bind(body.nextReviewAt||Date.now(),body.id,user.userId).run(); await d.prepare('INSERT INTO review_logs (card_id,direction,result,reviewed_at) VALUES (?,?,?,?)').bind(body.id,body.direction||'ja-en',body.result?1:0,Date.now()).run(); return Response.json({ok:true}); }
